export const CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID;

export const NFT_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;

export const SHOP_COIN_CONTRACT_ADDRESS = process.env.NEXT_PUBLIC_SHOP_COIN_CONTRACT_ADDRESS;

export const SIGNER = process.env.NEXT_PUBLIC_SIGNER;

export const PROJECT_ACCESS_KEY = process.env.NEXT_PUBLIC_PROJECT_ACCESS_KEY;

export const AUTHORIZATION_TOKEN = process.env.NEXT_PUBLIC_AUTHORIZATION_TOKEN;

